[ODS-5665] Add ability to query organizations by an identification code
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #1166
Opened 2024-10-17 15:32 UTC by mjaksn

2024-10-22 22:34 UTC, gmcelhanon requested changes

2024-10-22 22:34 UTC, gmcelhanon commented on Application/EdFi.Ods.Tests/EdFi.Ods.Common/Providers/ResourceIdentificaitonCodeProviderTests.cs
> +        public void TryFindIdentificationCodes_ShouldReturnTrueAndCorrectIdentificationCodeProperties_WhenABaseResourceHasIdentificationCode()
Maybe rename this to remove "Base" from the final name segment? Course is not really a base class, and it fits with the test above which is testing `WhenResourceHasNoIdentificationCode` -- maybe just use `WhenResourceHasIdentificationCode`?

2024-10-22 22:34 UTC, gmcelhanon commented on Application/EdFi.Ods.Tests/EdFi.Ods.Common/Providers/ResourceIdentificaitonCodeProviderTests.cs
> +        public void TryFindIdentificationCodes_ShouldReturnTrueAndCorrectIdentificationCodeProperties_WhenADerivedResourceHasIdentificationCode()
Definitely optional ... you could go with `WhenADerivedResourceHasInheritedIdentificationCode` here.

2024-10-22 22:34 UTC, gmcelhanon commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite GetByExample Tests.postman_collection.json
> +									"raw": "{{ApiBaseUrl}}/data/v3/ed-fi/localEducationAgencies?educationOrganizationIdentificationSystemDescriptor=uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor%23non-exis
Correct the spelling on `non-existent`...

2024-10-22 22:34 UTC, gmcelhanon commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite GetByExample Tests.postman_collection.json
> +					"name": "When filtering by IdentificationCode",
I feel like these tests could really use some negative test data (data that would show up in the results if the implementation was incorrect).  For example, in a "Setup" folder create a new temporary School that has identification codes that match the value being searched but uses a different identification system. (Also add a "Teardown" folder that removes this School and use a separate subfolder in between to hold the test requests, as necessary).

So, for example, create a School with an identification code that uses `uri://ed-fi.org/EducationOrganizationIdentificationSystemDescriptor#Other` with a value of `255901001`. This school should also be returned when only searching by identification code `255901001` but should not be returned if both the identification system and code are used in the search.

![image](https://github.com/user-attachments/assets/3c515dc5-586b-422e-b3af-81169220bfd3)

2024-10-24 21:45 UTC, gmcelhanon requested changes

2024-10-24 22:42 UTC, mjaksn commented on Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataPathsFactory.cs
> +                                name = (x.DescriptorName ?? x.PropertyName).ToCamelCase(),
I was thinking of entities and concerned descriptor property names could be suffixed with `Id`. That's not an issue with resources, so I changed it to only use `PropertyName` in the latest commit.

2024-10-25 19:41 UTC, gmcelhanon approved these changes

2024-10-25 19:41 UTC, merged