[ODS-4444] Finish EdFi.Ods.Test conversion
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #139
Opened 2020-09-03 09:20 UTC by BhanuprakashThunga

2020-09-03 13:31 UTC, jamessmckay requested changes

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/TestFixtureBase.cs
> +                EstablishContext();
The intent was not to modify this file, so what means any tests that had EstablishContext should be moved to Arrange, and ExecuteBehaviour should be moved to Act.

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/TestFixtureBase.cs
> +                ExecuteBehavior();
please revert

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/TestFixtureBase.cs
> +        protected virtual void ExecuteBehavior() { }
please revert

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/ScenarioFor.cs
> +            return (TSupplied)Supplied(tag);
fix formatting

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/ScenarioFor.cs
> +            SystemUnderTest = (TSystemUnderTest)_constructor.Invoke(args);
fix formatting please

2020-09-03 13:31 UTC, jamessmckay commented on tests/EdFi.TestFixture/ScenarioFor.cs
> +                    new[] { dependencyValue });
fix formatting please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateConfigurator.cs
> +            var path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
what is driving this change?

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateConfigurator.cs
> +                    var hbmSubclasses = _extensionDerivedEntityByEntityName[entityName].Select(x => (object)x).ToArray();
revert formatting please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateConfigurator.cs
> +                            .Select(x => (object)x)
revert formatting please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateConfigurator.cs
> +                            .Select(x => (object)x)
revert formatting please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Features/Controllers/AggregateDependencyController.cs
> +
revert fromatting please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +using Microsoft.AspNetCore.Http;
so this is looking to be net framework and net core app please confirm

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +using Microsoft.AspNetCore.Http;
I just checked there are a lot of unused references that need to be cleaned up including the references to net framework.

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +
remove blank line

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +
This file also needs a reformat

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +            request.RouteValues = new RouteValueDictionary { {
formatting needs to be fixed here please

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +    public class When_calling_the_token_controller
we should wrap the all the tests in a class named TokenControllerTests. It should have the [TestFixture] attribute so the tests are aggregated. 

Note this is a nice to have

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +            [TestFixture]
remove the test fixture here please since you are using test fixture base

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +
remove blank line

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +                    A.CallTo(() => _clientAppRepo.GetClientAsync(A<string>._)).Returns(_suppliedClient);
I think we have an issue here, we are using async methods, and you should be returning a Task.FromResult(). Secondly the test base framework is not designed to be async, and we should consider rewritting these tests using the AAA syntax and using  async.

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +                    var result = (OkObjectResult)_actionResult;
the asserts should be _actionResult.ShouldBeOfType<OkObjectResult>() (i cant remember the syntax please look it up).
_actionResult.StatusCode.ShouldBe(HttpStatusCode.Ok)

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +                    //        }));
why is this commented out?

2020-09-03 13:31 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +            // TODO: ODS-4430 ...
why not addressed?

2020-09-04 14:00 UTC, jamessmckay commented on Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
> +    <TargetFrameworks>netcoreapp31</TargetFrameworks>
we need to run these tests on both frameworks please

2020-09-04 14:01 UTC, jamessmckay commented on Application/Test.Common/LegacyScenarioFor.net.cs
> +                    .FirstOrDefault();
```suggestion
                .FirstOrDefault();
```

2020-09-04 14:01 UTC, jamessmckay commented on Application/Test.Common/LegacyScenarioFor.net.cs
> +            return (TDependency)list[1];
```suggestion
            return (TDependency) list[1];
```

2020-09-07 07:02 UTC, BhanuprakashThunga commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Controllers/TokenControllerTests.cs
> +                // }
@jamessmckay  syed is working on this part , already discussed with syed on this test case. Once he implements will enable this.

2020-09-07 07:07 UTC, BhanuprakashThunga commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/Infrastructure/Pipelines/Steps/PersistModelTests.cs
> +                step.ExecuteAsync(context, _putResult, CancellationToken.None).WaitSafely();
Fixed

2020-09-07 07:21 UTC, BhanuprakashThunga commented on Application/EdFi.Ods.Tests/EdFi.Ods.Common/Infrastructure/Configuration/NHibernateConfiguratorTests.cs
>  namespace EdFi.Ods.Tests.EdFi.Ods.WebApi.NHibernate.Architecture
Renamed the namespace to EdFi.Ods.Tests.EdFi.Ods.Common.Infrastructure.ConfigurationTest . Appended test at last of namespace as the Configuration class from NHibernate.cfg throwing extension issue

2020-09-07 18:41 UTC, jamessmckay approved these changes

2020-09-08 12:41 UTC, merged