[ODS-4409] Moving Swagger Document Generation to use IoC
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #153
Opened 2020-09-10 09:37 UTC by BhanuprakashThunga

2020-09-10 12:50 UTC, jamessmckay requested changes

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDocumentFactory.cs
> +                    .ToList();
These should be local variables

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDocumentFactory.cs
> +        private static OpenApiMetadataTagsFactory _tagsFactory;
this should be remove and converted to local variables

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDocumentFactory.cs
>      public class OpenApiMetadataDocumentFactory
we should create an interface for this class

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Factories/OpenApiMetadataDocumentFactoryHelper.cs
> -            );
this change is odd did you test the generation of the documents?

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Providers/OpenApiMetadataCacheProvider.cs
> + new ConcurrentDictionary<string, OpenApiContent>(StringComparer.InvariantCultureIgnoreCase);
formatting issue?

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Providers/OpenApiMetadataCacheProvider.cs
> +                                        .Create(x.Value, new OpenApiMetadataDocumentContext(_resourceModelProvider.GetResourceModel()))),
ultimately we will inject the document factory into the cache provider, and this will be _openApiMetadataDocumentFactory.Create(....)

2020-09-10 12:50 UTC, jamessmckay commented on Application/EdFi.Ods.Features/OpenApiMetadata/Providers/OpenApiMetadataCacheProvider.net.cs
> +                                    new OpenApiMetadataDocumentFactory(
this is fine for the legacy stuff, we will be removing it shortly.

2020-09-11 05:44 UTC, closed without merging

2020-09-11 05:44 UTC, BhanuprakashThunga commented
Need to create .net.cs files for the Modified files .Creaing the new PR for the same closing this