[ODS-4456] Standardize on using IDomainModelProvider
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #162
Opened 2020-09-16 17:53 UTC by raghuramakrishna

2020-09-17 12:55 UTC, jamessmckay commented on Application/EdFi.Ods.Repositories.NHibernate.Tests/Modules/DomainModelModule.cs
> +            builder.RegisterType<DomainModelProvider>().As<IDomainModelProvider>();
the more i think about this, we should have a singleton for the domain model provider

2020-09-17 12:56 UTC, jamessmckay approved these changes

2020-09-17 19:34 UTC, blmeyers requested changes
Looks like this needs a rebase to get a clean build, due to the test changes that went in today.

2020-09-18 19:12 UTC, blmeyers approved these changes

2020-09-21 00:56 UTC, merged