[ODS-4410] Convert all usages of \r\n in source code to use Environment.NewLine constant
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #198
Opened 2020-10-09 14:44 UTC by tparandiev

2020-10-09 19:46 UTC, blmeyers requested changes
Almost there.

2020-10-12 13:03 UTC, tparandiev commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslatorTests.cs
> +                string mess =
It's not possible to declare a local variable as a read-only.

2020-10-12 13:03 UTC, tparandiev commented on Application/EdFi.Ods.Tests/EdFi.Ods.Api/ExceptionHandling/Translators/SqlServer/DuplicateNaturalKeyCreateExceptionTranslatorTests.cs
> +                string mess =
It's not possible to declare a local variable as a read-only.

2020-10-12 14:27 UTC, blmeyers approved these changes

2020-10-12 14:27 UTC, merged