[ODS-4297] Cleanup .net.cs files and pre-processor directives
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #199
Opened 2020-10-12 09:45 UTC by BhanuprakashThunga

2020-10-13 19:45 UTC, blmeyers requested changes
Addressed a few areas in comments, but in general:

1. Don't explicitly include folders in the csprojs, particularly when they're folders that are being deleted.
2. Make sure we're cleaning up all the code we're deleting, not just excluding it.
3. Revisit all the csproj files.  There are still cases of framework checks sticking around, both for standard and for net48.  After this PR there should be no more conditional includes in the csproj files.
4. There are still 43 files with #if conditionals.  Please make sure we're removing the conditional if its for NETSTANDARD or CORE, and that we're deleting the file if its for net48.
5. Take a pass through all the projects and make sure we've cleaned up all the .config files except the web.configs in the web projects for IIS support.  There should not be any more app configs now. Also clean up the hack in the csproj for copying the app.config for some of the test projects.

2020-10-13 19:45 UTC, blmeyers commented on Application/EdFi.Ods.Tests/EdFi.Ods.Tests.csproj
> +  </ItemGroup>
```suggestion
```

2020-10-13 19:45 UTC, blmeyers commented on Application/EdFi.Ods.Tests/_Extensions/ExceptionAssertionExtensions.cs
> +                Actual Exception: {exception}");
Revert extra formatting changes please.

2020-10-13 19:45 UTC, blmeyers commented on tests/EdFi.Common.UnitTests/EdFi.Common.UnitTests.csproj
> +  </ItemGroup>
```suggestion
```

2020-10-14 21:02 UTC, jamessmckay approved these changes

2020-10-15 00:17 UTC, blmeyers approved these changes

2020-10-15 00:18 UTC, merged