[ODS-4234] Add postman tests for EdOrg types added by an Extension
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #243
Opened 2020-12-01 00:51 UTC by semalaiappan

I added postman tests for EdOrg types added by an Extension 

I also added disabled postman scripts for ODS-4637 which is used as manual run in future

2020-12-01 16:22 UTC, blmeyers requested changes
Mostly minor changes, but need to decide if we're testing get by id or get by example for verifying after the update.

2020-12-01 16:22 UTC, blmeyers commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"     pm.expect(responseItems.endDate).to.be.equal(pm.environment.get(\"endDate\"));",
```suggestion
									"    var responseItem = pm.response.json();",
									"     pm.expect(responseItem.endDate).to.be.equal(pm.environment.get(\"endDate\"));",
```

2020-12-01 16:22 UTC, blmeyers commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"     pm.expect(responseItems.staffReference.staffUniqueId).to.be.equal(pm.environment.get(\"known:staffUniqueId\"));",
```suggestion
									"    var responseItem = pm.response.json();",
									"     pm.expect(responseItem.staffReference.staffUniqueId).to.be.equal(pm.environment.get(\"known:staffUniqueId\"));",
```

2020-12-01 16:22 UTC, blmeyers commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"     pm.expect(responseItems.gradeLevels[0].gradeLevelDescriptor).to.be.equal(pm.environment.get(\"gradeLevelDescriptor\"));",
```suggestion
									"    var responseItem = pm.response.json();",
									"     pm.expect(responseItem.gradeLevels[0].gradeLevelDescriptor).to.be.equal(pm.environment.get(\"gradeLevelDescriptor\"));",
```

2020-12-01 16:22 UTC, blmeyers commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"     pm.expect(responseItems.staffReference.staffUniqueId).to.be.equal(pm.environment.get(\"known:staffUniqueId\"));",
```suggestion
									"    var responseItem = pm.response.json();",
									"     pm.expect(responseItem.staffReference.staffUniqueId).to.be.equal(pm.environment.get(\"known:staffUniqueId\"));",
```

2020-12-02 02:04 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS API v3.x (Local).postman_environment.disabled.json
> +{
File removed

2020-12-02 02:04 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite - Publishing Feature.postman_collection.disabled
> +{
File removed

2020-12-02 04:14 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +					"name": "Get a University by nameOfInstitution",
@blmeyers - I removed query string parameter and looping response array to check nameOfInstitution

2020-12-02 04:15 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"    var responseItems = pm.response.json();",
@blmeyers - I removed query string parameter and looping response array to check nameOfInstitution

2020-12-02 04:25 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +					"name": "Clean up  teacherCandidateTeacherPreparationProviderProgramAssociation Data",
I removed eaning up TeacherCandidateTeacherPreparationProviderProgramAssociation data

2020-12-02 04:26 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +					"name": "Get a teacherPreparationProvider by nameOfInstitution",
@blmeyers   I removed query string parameter and looping response array to check nameOfInstitution

2020-12-07 14:30 UTC, blmeyers requested changes

2020-12-07 14:30 UTC, blmeyers commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"    var responseItems = pm.response.json();",
You removed too much here.  Now you're just doing a get all, which might work for now but if we ever add more sample data you run the risk of your added entry not coming back on an initial request and requiring paging to reach.  What you had before was fine, you were just mixing two approaches.  This should likely be just using GetById (so pass the Id in the route) and then verify that the item got updated.  We're not trying to test GetAll or GetByExample for these test cases. Same for the other places you did get verification.

2020-12-07 15:40 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +									"    var responseItems = pm.response.json();",
@blmeyers   I updated to based on By ID and validate the name of institution in response result . Thanks

2020-12-07 15:40 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API TPDM Test Suite.postman_collection.json
> +					"name": "Get a University by nameOfInstitution",
@blmeyers   I updated to based on By ID and validate the name of institution in response result . Thanks

2020-12-07 15:40 UTC, semalaiappan commented
@blmeyers - Please review it again . Thank you !

2020-12-07 15:55 UTC, blmeyers approved these changes
Looks good, just waiting on the last build to finish.

2020-12-07 16:02 UTC, merged