[ODS-4731] Package XSD Metadata in Deployed ODS/API - Extensions
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #257
Opened 2020-12-18 17:16 UTC by semalaiappan

2020-12-23 20:38 UTC, blmeyers requested changes
Since we're rebuilding against the TPDM tag, we shouldn't be disabling any tests.

2020-12-28 17:08 UTC, semalaiappan commented
Reviewer - Please read this slack link for why we created branch from 5.1.0 tag for this ticket
https://ed-fi-alliance.slack.com/archives/GFYL23ATW/p1608649810429300

2021-01-04 15:06 UTC, jamessmckay approved these changes

2021-01-05 21:10 UTC, semalaiappan commented
@blmeyers As Discussed in Standup  ,  I removed  TPDM Extension changes now and will be  handle later  in new ticket ODS-4760

2021-01-06 16:05 UTC, blmeyers approved these changes

2021-01-06 16:05 UTC, merged