[ODS-4831] Update Load Tools Documentation
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #293
Opened 2021-03-15 14:28 UTC by raghuramakrishna

2021-03-16 18:22 UTC, vimayya commented
@raghuramakrishna ODS-4398 added baseurl to smoke test and xml lookup utilities as well, can you extend the PR to indicate deprecation there as well?

2021-03-16 19:11 UTC, tbmeador-dlp requested changes
xsd option needs to be deprecated:
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/bcac24cb24172ccf629eeae6b029eb270e81b07a/Utilities/DataLoading/EdFi.BulkLoadClient.Console/Application/CommandLineOverrides.cs#L47

2021-03-17 06:58 UTC, raghuramakrishna commented on Utilities/DataLoading/EdFi.BulkLoadClient.Console/Application/CommandLineOverrides.cs
> +        [Option('c', "connectionlimit", Required = false, HelpText = "(deprecated) Max number of simultaneous API requests")]
@tbmeador-dlp  connectionlimit and maxrequests are both same. Should I keep it as it is?

2021-03-17 08:51 UTC, raghuramakrishna commented on Utilities/DataLoading/EdFi.BulkLoadClient.Console/Application/CommandLineOverrides.cs
> +        [Option('c', "connectionlimit", Required = false, HelpText = "(deprecated) Max number of simultaneous API requests")]
Also I dont see instance-id being used anywhere other than declaration. Do we still need it?

2021-03-19 14:09 UTC, tbmeador-dlp requested changes
updates look good, need to rebase to resolve conflicts

2021-03-19 15:18 UTC, vimayya commented on Utilities/DataLoading/EdFi.XmlLookup.Console/Application/CommandLineOverrides.cs
>          [Option('b', "baseUrl", Required = false, HelpText = "The base url")]
@raghuramakrishna while you are at it, could you bring baseUrl to the top of this list so that is shows first when --help is called

2021-03-19 18:39 UTC, tbmeador-dlp approved these changes
Looks good!

2021-03-19 18:42 UTC, merged