[ODS-4941] Collapse EdFi.Ods.Security into a namespace in EdFi.Ods.Api
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #314
Opened 2021-05-11 12:25 UTC by raghuramakrishna

2021-05-12 18:25 UTC, blmeyers requested changes

2021-05-13 09:55 UTC, raghuramakrishna commented on Application/EdFi.Ods.Api/Security/Authorization/IEducationOrganizationCacheDataProvider.cs
> +namespace EdFi.Ods.Api.Security.Authorization {
updated

2021-05-13 15:19 UTC, jamessmckay approved these changes

2021-05-13 16:41 UTC, raghuramakrishna commented on Application/EdFi.Ods.Api/Security/Marker_EdFi_Ods_Security.cs
> +namespace EdFi.Ods.Api.Security
@jamessmckay this is already removed

2021-05-13 16:46 UTC, blmeyers approved these changes

2021-05-13 20:36 UTC, merged