[ODS-5026] Create "Ed-Fi ODS Admin App" and "AB Connect" claimsets during the EdFi_Security database setup/ creation
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #344
Opened 2021-08-11 13:42 UTC by tnunnerydl

2021-08-11 18:53 UTC, semalaiappan requested changes

2021-08-11 18:53 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +WHERE NOT EXISTS (SELECT *
```suggestion
WHERE NOT EXISTS (SELECT 1
```

2021-08-11 18:53 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +WHERE NOT EXISTS (SELECT *
```suggestion
WHERE NOT EXISTS (SELECT 1
```

2021-08-11 18:53 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +WHERE NOT EXISTS (SELECT *
```suggestion
WHERE NOT EXISTS (SELECT 1
```

2021-08-11 18:53 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +WHERE NOT EXISTS (SELECT *
```suggestion
WHERE NOT EXISTS (SELECT 1
```

2021-08-11 18:53 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +WHERE a.ActionName in ('Read','Create') AND NOT EXISTS (SELECT *
```suggestion
WHERE a.ActionName in ('Read','Create') AND NOT EXISTS (SELECT 1
```

2021-08-11 18:55 UTC, semalaiappan requested changes

2021-08-11 18:55 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +PRINT 'Creating temorary records.'
```suggestion
PRINT 'Creating Temporary Records.'
```

2021-08-11 18:55 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +PRINT 'Creating temorary records.'
```suggestion
PRINT 'Creating Temporary Records.'
```

2021-08-12 13:57 UTC, semalaiappan approved these changes

2021-08-12 13:57 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO ClaimSets (ClaimSetName, Application_ApplicationId)
```suggestion
INSERT INTO dbo.ClaimSets (ClaimSetName, Application_ApplicationId)
```

2021-08-12 13:57 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @actionId = ActionId FROM Actions WHERE ActionName = @actionName
tables requires to have dbo. before the table name . Please check

2021-08-12 13:58 UTC, semalaiappan requested changes
Formatting is required for Sql scripts . Please check other scripts here for reference Ed-Fi-ODS\Artifacts\MsSql\Data\Security

2021-08-12 14:16 UTC, semalaiappan requested changes

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @applicationId = ApplicationId FROM  Applications WHERE ApplicationName = @applicationName
```suggestion
SELECT @applicationId = ApplicationId FROM  dbo.Applications WHERE ApplicationName = @applicationName
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT DISTINCT @claimSetName, @applicationId FROM ClaimSets
```suggestion
SELECT DISTINCT @claimSetName, @applicationId FROM dbo.ClaimSets
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +                  FROM ClaimSets
```suggestion
                  FROM dbo.ClaimSets
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @actionId = ActionId FROM Actions WHERE ActionName = @actionName
```suggestion
SELECT @actionId = ActionId FROM dbo.Actions WHERE ActionName = @actionName
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO ClaimSetResourceClaims
```suggestion
INSERT INTO dbo.ClaimSetResourceClaims
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT ActionId, @claimSetId, ResourceClaimId , @authorizationStrategyId FROM Actions a, @resourceClaimIds rc
```suggestion
SELECT ActionId, @claimSetId, ResourceClaimId , @authorizationStrategyId FROM dbo.Actions a, @resourceClaimIds rc
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @actionId = ActionId FROM Actions WHERE ActionName = 'Read'
```suggestion
SELECT @actionId = ActionId FROM dbo.Actions WHERE ActionName = 'Read'
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @ResourceClaimId = ResourceClaimId FROM ResourceClaims WHERE ResourceName = 'types'
```suggestion
SELECT @ResourceClaimId = ResourceClaimId FROM dbo.ResourceClaims WHERE ResourceName = 'types'
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO ClaimSetResourceClaims
```suggestion
INSERT INTO dbo.ClaimSetResourceClaims
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO ClaimSets (ClaimSetName, Application_ApplicationId)
```suggestion
INSERT INTO dbo.ClaimSets (ClaimSetName, Application_ApplicationId)
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +                  FROM ClaimSets
```suggestion
                  FROM dbo.ClaimSets
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO @resourceClaimIds SELECT ResourceClaimId FROM ResourceClaims WHERE ResourceName IN (SELECT ResourceName FROM @resourceNames)
```suggestion
INSERT INTO @resourceClaimIds SELECT ResourceClaimId FROM dbo.ResourceClaims WHERE ResourceName IN (SELECT ResourceName FROM @resourceNames)
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @actionId = ActionId FROM Actions WHERE ActionName = @actionName
```suggestion
SELECT @actionId = ActionId FROM dbo.Actions WHERE ActionName = @actionName
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +SELECT @claimSetId = ClaimSetId FROM ClaimSets WHERE ClaimSetName = @claimSetName
```suggestion
SELECT @claimSetId = ClaimSetId FROM dbo.ClaimSets WHERE ClaimSetName = @claimSetName
```

2021-08-12 14:16 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +INSERT INTO ClaimSetResourceClaims
```suggestion
INSERT INTO dbo.ClaimSetResourceClaims
```

2021-08-13 14:20 UTC, vimayya commented
@tbmeador-dlp, @semalaiappan my understanding is that these scripts need to be idempotent. I am seeing additional records being inserted on ClaimSetResourceClaims when run more than once.

2021-08-16 13:11 UTC, semalaiappan approved these changes

2021-08-16 13:12 UTC, merged