ODS-5070 - Handle TargetInvocationException so correct validation results gets returned from api
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #394
Opened 2021-11-11 23:39 UTC by bptillman

When sending an invalid calendarTypeDescriptoron the Calendar POST, a TargetInvocationException was being thrown, which then prevented the validation results from being returned by the API. Now we will catch this and then log the correct validation error.

Additionally, the Trace.Errors were swapped out for using log4net so that these types of messages could be seen in the WebApiLog.

2021-11-12 06:15 UTC, gmcelhanon requested changes
This is one of those that it would be easy and good to add a simple unit test for coverage. I reproduced the problem in Linqpad, but here's the basic approach.

Declare a test class with a validation attribute that throws an exception when its value is retrieved, like so:
```csharp
public class ClassWithValidationThrowingException
{
	private string _value;
	
	[RequiredWithNonDefault]
	public string Value
	{
		get => throw new Exception("Test validation failure message.");
		set => _value = value;
	}
}
```

The unit test body should execute the validation as follows (add appropriate assertions):
```csharp
    var p = new ClassWithValidationThrowingException { Value = "Abc" };
	
    var validators = new IEntityValidator[] { new DataAnnotationsEntityValidator() };
    var results = validators.ValidateObject(p);

    // Assert that validation failed and that the validation message is the exception text from the test class.
```
Follow conventions and put the class in this folder:
![image](https://user-images.githubusercontent.com/1467340/141419115-47d70b63-ebff-42aa-99e7-8467da490d49.png)

We have 2 main styles of unit tests. A more traditional barebones NUnit test fixture with individual wholly contained test methods named like `When_doing_this_thing_should_see_this_result`.  Alternatively, you can inherit from `TestFixtureBase` and override Arrange/Assert/Act methods to write the test. This is generally reserved for more involved unit tests with dependencies and involves Acting once in the fixture, saving the results for subsequent inspection in individual assertions declared as test methods.

2021-11-15 14:40 UTC, bptillman commented
> ```cs
> 	private string _value;
> 	
> 	[RequiredWithNonDefault]
> 	public string Value
> 	{
> 		get => throw new Exception("Test validation failure message.");
> 		set => _value = value;
> 	}
> ```

A new test has been added per your guidelines here.

2021-11-16 21:43 UTC, gmcelhanon approved these changes

2021-11-16 22:42 UTC, semalaiappan approved these changes

2021-11-16 22:42 UTC, merged