[ODS-5191] Record Ownership Phase 2 - Update existing migration scripts to use new tables
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #404
Opened 2021-12-09 13:25 UTC by raghuramakrishna

2021-12-09 14:57 UTC, semalaiappan commented
@raghuramakrishna please rebase your branch with  feature-RecordOwnershipPhase2 .  Then update table name and new columns in your script in sql server and postgres

2021-12-09 15:21 UTC, semalaiappan requested changes

2021-12-09 15:21 UTC, semalaiappan commented on Artifacts/PgSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +	INNER JOIN dbo.ResourceClaimActionAuthorizations
update new table and columns here from this 
![image](https://user-images.githubusercontent.com/34613894/145424036-9f2d0ad6-1be6-4233-a053-721651e46440.png)

2021-12-09 17:07 UTC, semalaiappan commented
@raghuramakrishna  bring these scripts also from old PR 
![image](https://user-images.githubusercontent.com/34613894/145442866-084800d4-75c8-4cae-a5e4-d93d0226c00a.png)

2021-12-10 17:45 UTC, semalaiappan requested changes

2021-12-10 17:45 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/1030-DataStandard3.3a-ResourceClaimMetadata.sql
> +	INNER JOIN [dbo].[ResourceClaims] r ON
Inner join is missing dbo.ClaimSets
    WHERE ClaimSetName IN ('SIS Vendor','Ed-Fi Sandbox','District Hosted SIS Vendor')

2021-12-10 17:45 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/1070-OrganizationDepartmentMetadata.sql
> -IF NOT EXISTS (SELECT 1 FROM dbo.ClaimSetResourceClaims csrc INNER JOIN dbo.ClaimSets cs ON csrc.ClaimSet_ClaimSetId = cs.ClaimSetId WHERE cs.ClaimSetName = 'District Hosted SIS Vendor' AND csrc.Reso
dbo.ResourceClaimAuthorizationMetadatas is old table  and new table is ResourceClaimActions  . this line needs to be updated IF NOT EXISTS (SELECT 1 FROM dbo.ResourceClaimAuthorizationMetadatas WHERE ResourceClaim_ResourceClaimId = @organizationDepartmentClaimId)

2021-12-10 17:45 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/1070-OrganizationDepartmentMetadata.sql
> -IF NOT EXISTS (SELECT 1 FROM dbo.ClaimSetResourceClaims csrc INNER JOIN dbo.ClaimSets cs ON csrc.ClaimSet_ClaimSetId = cs.ClaimSetId WHERE cs.ClaimSetName = 'District Hosted SIS Vendor' AND csrc.Reso
INSERT INTO dbo.ResourceClaimAuthorizationMetadatas(ResourceClaim_ResourceClaimId, Action_ActionId, AuthorizationStrategy_AuthorizationStrategyId)  dbo.ResourceClaimAuthorizationMetadatas is old table and new table is ResourceClaimActions .

2021-12-10 17:45 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
>  SELECT @claimSetId = ClaimSetId FROM dbo.ClaimSets WHERE ClaimSetName = @claimSetName
SELECT @actionId = ActionId FROM dbo.Actions WHERE ActionName = @actionName  . Where is set value for @actionName variable

2021-12-10 17:45 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +                  FROM dbo.ClaimSetResourceClaimActions
missing with condition AND ResourceClaimId = rc.ResourceClaimId in if not exists

2021-12-10 17:45 UTC, actionname commented
您好！我已经收到你的邮件我会尽快回复你，谢谢！                                            

2021-12-10 17:56 UTC, semalaiappan requested changes

2021-12-10 17:56 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +	AND a.ActionName in ('READ')
change to 'Read' even though sql server is not case sensitive language

2021-12-10 22:48 UTC, semalaiappan requested changes

2021-12-10 22:48 UTC, semalaiappan commented on Artifacts/MsSql/Data/Security/2000-AdminApp-ClaimSets.sql
> +                  FROM dbo.ClaimSetResourceClaimActions
IF NOT EXISTS (SSELECT 1
                  FROM dbo.ClaimSetResourceClaimActions csraa,dbo.Actions a, @resourceClaimIds rc
				  WHERE csraa.ActionId = a.ActionId AND ClaimSetId = @claimSetId AND csraa.ResourceClaimId = rc.ResourceClaimId)

2021-12-10 23:07 UTC, semalaiappan requested changes

2021-12-10 23:07 UTC, semalaiappan commented on Artifacts/PgSql/Data/Security/1070-OrganizationDepartmentMetadata.sql
> +	IF NOT EXISTS (SELECT 1 FROM dbo.ResourceClaimAuthorizationMetadatas WHERE ResourceClaim_ResourceClaimId = organization_department_claim_id)
ResourceClaimAuthorizationMetadatas is old table  , please update with new table . refer sql server version script

2021-12-13 00:56 UTC, semalaiappan commented
@raghuramakrishna   Count for 4 tables should be matching for Sql server and Postgres .  Validate that in your local run for both database .

2021-12-13 16:26 UTC, semalaiappan commented
@raghuramakrishna  ClaimSetResourceClaimActionAuthorizationStrategyOverrides table record count is mismatch with Sql server and Postgres now .

2021-12-13 16:50 UTC, merged

2021-12-13 16:51 UTC, semalaiappan commented
As All 4 tables changes are looks good .   Integration builds failure will be fixed in separate ticket, So  I am merging this ticket .