[ODS-5193] Record Ownership Phase 2 - Add script to cleanup old tables
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #406
Opened 2021-12-10 22:28 UTC by tbmeador-dlp

2021-12-28 20:42 UTC, gmcelhanon requested changes

2021-12-29 16:50 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/Authorization/AuthorizationSegmentsVerifier.cs
> +                            + $"{subjectEndpointNamesText} value. (Authorization Strategy: {authorizationStrategyName})";
fixed it

2021-12-29 16:50 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/Authorization/AuthorizationSegmentsVerifier.cs
> +                        + $"the requested resource: {subjectEndpointNamesText}. (Authorization Strategy: {authorizationStrategyName})";
fixed it

2021-12-29 16:50 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/AuthorizationSegmentsToFiltersConverter.cs
> +                            AuthorizationStrategyName = segment.AuthorizationStrategyName
fixed it

2021-12-29 16:50 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationStrategyBase.cs
> +                            claimsAuthorizationSegment.AuthorizationStrategyName));
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationStrategyBase.cs
> +            foreach (var authorizationSegment in authorizationSegments)
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationStrategyBase.cs
> +            var segments = builder.GetSegments();
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Application/EdFi.Ods.Common/Security/Authorization/ClaimsAuthorizationSegment.cs
> +        /// <summary>
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Application/EdFi.Ods.Common/Security/Authorization/ClaimsAuthorizationSegment.cs
> +            string authorizationPathModifier,
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Application/EdFi.Ods.Common/Security/Authorization/ClaimsAuthorizationSegment.cs
> +            AuthorizationStrategyName = authorizationStrategyName;
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite Multiple Edorg types.postman_collection.json
> +											"        pm.expect(responseItems.message).to.equal(\"Authorization denied. No relationships have been established between the caller's education organization id claim (value [5001] of type
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite Multiple Edorg types.postman_collection.json
> +											"        pm.expect(responseItems.message).to.equal(\"Authorization denied. No relationships have been established between the caller's education organization id claim (value [5001] of type
fixed it

2021-12-29 16:51 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite Multiple Edorg types.postman_collection.json
> +											"        pm.expect(responseItems.message).to.equal(\"Authorization denied. No relationships have been established between the caller's education organization id claim (value [255901001] of
fixed it

2021-12-29 16:52 UTC, semalaiappan commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
> +									"     pm.expect(responseItem.message).to.include(\"Authorization denied. No relationships have been established between the caller's education organization id claim (value [255901] of type '
fixed it

2021-12-29 17:40 UTC, semalaiappan commented on Application/EdFi.Ods.Common/Security/Authorization/AuthorizationFilterDetails.cs
> +
fixed it

2021-12-29 23:38 UTC, gmcelhanon approved these changes

2021-12-29 23:38 UTC, merged