[ODS-4835] Code Generation for Resource Links to some Base Aggregates Fail
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #436
Opened 2022-02-14 06:11 UTC by gmcelhanon

Removing unused references to base property mappings to fix issues with link generation for GeneralStudentProgramAssociation links.

2022-02-18 19:04 UTC, bptillman requested changes

2022-02-18 19:56 UTC, gmcelhanon reviewed
As discussed on Slack, the unused methods have also been removed through an additional commit by @bptillman .

2022-03-01 19:33 UTC, gmcelhanon reviewed
Since I opened the PR, I can't Request Changes, but I am requesting a change here.

2022-03-01 19:33 UTC, gmcelhanon commented on tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/Steps.cs
> +                    WHERE sc.LocalEducationAgencyId IS NOT NULL";
@bptillman I was thinking we would tap into the EducationOrganizationIdToEducationOrganizationId authorization view to identify a StudentSchoolAssociation that is accessible to the test client here. With the `IS NOT NULL` check that you've added here, It is still conceivable that we could end up with the same problem if another school was created for testing purposes like the one we saw in the test ODS for SchoolId = 7 except with the LocalEducationAgencyId set.

What do you think about making this a more durable query -- something like the following:

```sql
SELECT  TOP 1 ssa.Id
FROM    edfi.StudentSchoolAssociation ssa
        INNER JOIN auth.EducationOrganizationIdToEducationOrganizationId edOrgs
            ON ssa.SchoolId = edOrgs.TargetEducationOrganizationId
WHERE edOrgs.SourceEducationOrganizationId = 255901
```

2022-03-02 00:23 UTC, gmcelhanon commented
@bptillman I approve of the changes, but I opened the original PR and cannot merge it. Please feel free to merge when ready.

2022-03-02 00:24 UTC, bptillman approved these changes

2022-03-02 00:24 UTC, merged