ODS-5303 - Move Admin.DataAccess build to GithubActions
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #454
Opened 2022-03-14 22:19 UTC by bptillman

This creates two new GithubActions, one workflow that can be manually triggered and a second that gets triggered on a pull request to main. The manually triggered one mimics what exists in TeamCity right now to build, test, pack, and publish, while the pull request one will only run a build and test.

You will not see the ability to manually run the github workflow since it has to exist in main first before it will show up there, so to test these workflows out I forked ODS, applied the workflows in the main branch and then tested them there in the fork.

2022-03-21 14:29 UTC, semalaiappan requested changes
Overall looks good .  These 2 workflow names requires to have prefex with 'EdFi.Admin.DataAccess' so that to identify the builds from Github Actions build .  

Note : we need to have task to remove 10 from build counter as per part 5.4 release task as part of post activities

2022-03-21 16:38 UTC, bptillman commented
> Overall looks good . These 2 workflow names requires to have prefex with 'EdFi.Admin.DataAccess' so that to identify the builds from Github Actions build .
> 
> Note : we need to have task to remove 10 from build counter as per part 5.4 release task as part of post activities

[ODS-5346](https://tracker.ed-fi.org/browse/ODS-5346) has been added to tracking removing the 10 from the build counter post release

2022-03-21 18:09 UTC, vimayya commented on .github/workflows/shared.yml
> +    - uses: actions/checkout@v2
@bptillman could you please use commit hash instead of version number https://techdocs.ed-fi.org/display/EDFIODS/Guidelines+for+Use+of+GitHub+Actions

2022-03-22 15:27 UTC, semalaiappan requested changes
Warning: Unexpected input(s) 'dotnet-version', valid inputs are ['version'] in Setup.NET 
Please use version instead of dotnet-version
Reference https://github.com/actions/setup-dotnet/issues/90

2022-03-23 15:07 UTC, semalaiappan approved these changes

2022-03-23 15:08 UTC, merged