[ODS-5424] Update Tests to run against Postgres
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #506
Opened 2022-05-26 23:58 UTC by ericstockdale

2022-06-08 17:04 UTC, bptillman requested changes
Great job on this by the way. It was a lot of work. A lot more than we/I expected. The only issues I've made comments on are all minor and nothing structurally I can see that needs to change.

2022-06-10 17:49 UTC, ericstockdale commented on Application/EdFi.Ods.Repositories.NHibernate.Tests/BaseDatabaseTest.cs
> +using PostgresSpecificModule = EdFi.Ods.Repositories.NHibernate.Tests.Modules.PostgresSpecificModule;
Removed

2022-06-10 17:52 UTC, ericstockdale commented on Application/EdFi.Ods.Repositories.NHibernate.Tests/StudentProgramAssociationTests.cs
>                  using (var conn = GetSqlConnectionForOds())
Renamed

2022-06-10 17:55 UTC, ericstockdale commented on Application/EdFi.Ods.Repositories.NHibernate.Tests/StudentProgramAssociationTests.cs
> +using PostgresSpecificModule = EdFi.Ods.Repositories.NHibernate.Tests.Modules.PostgresSpecificModule;
Removed

2022-06-10 18:05 UTC, ericstockdale commented on tests/EdFi.Admin.DataAccess.IntegrationTests/appsettings.json
> +  "Engine": "PostgreSql"
Added comment to all settings.json and also made sure they were all sqlServer by default

2022-06-10 18:10 UTC, ericstockdale commented on tests/EdFi.Ods.WebApi.IntegrationTests/DbHelper.cs
> +        public static IConfigurationRoot GetDatabaseEngineSpecificConfiguration(DatabaseEngine databaseEngine)
Removed.  The other integration tests used this method.  However, WebApi.IntegrationTests uses a Host that runs the configuration builder so this method is inapplicable for this project.

2022-06-10 18:14 UTC, ericstockdale commented on tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/EnvironmentSetupTests.cs
> +using System.Data;
removed

2022-06-10 18:16 UTC, ericstockdale commented on tests/EdFi.Ods.WebApi.CompositeSpecFlowTests/Steps.cs
> +            string query = string.Empty;
removed

2022-06-10 20:11 UTC, bptillman approved these changes

2022-06-10 20:11 UTC, merged