[ODS-5459] Create AuthorizationContextDataProvider for role-named ResponsibilitySchoolId in Discipline Action
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #529
Opened 2022-07-12 21:38 UTC by ericstockdale

2022-07-13 15:33 UTC, gmcelhanon requested changes
Make the changes listed and let's see where we are.

2022-07-13 15:33 UTC, gmcelhanon commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationContextData.cs
> +            public const string ResponsibilitySchoolId = "ResponsibilitySchoolId";
This class only contains entries for the baseline EdOrg-derived properties. Role named properties are not "new" properties, they are contextual variations of the main ones. There should be no changes to this class.

2022-07-13 15:33 UTC, gmcelhanon commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationContextData.cs
> +        public int? ResponsibilitySchoolId { get; set; }
Remove this.

2022-07-13 15:33 UTC, gmcelhanon commented on Application/EdFi.Ods.Standard/Security/Authorization/Overrides/DisciplineActionRelationshipsAuthorizationContextDataProvider.cs
> +            contextData.ResponsibilitySchoolId = entity.ResponsibilitySchoolId; // Role name applied and not part of primary key
This should be:
```csharp
contextData.SchoolId = entity.ResponsibilitySchoolId; // Role name applied and not part of primary key
```

2022-07-14 13:27 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationContextData.cs
> +        public int? ResponsibilitySchoolId { get; set; }
OK Thanks  .  I removed it .

2022-07-14 13:27 UTC, semalaiappan commented on Application/EdFi.Ods.Api/Security/AuthorizationStrategies/Relationships/RelationshipsAuthorizationContextData.cs
> +                case PropertyNames.ResponsibilitySchoolId:
I removed it .

2022-07-21 01:15 UTC, closed without merging