ODS-5572 EdFi.Suite3.Ods.Api & EdFi.Suite3.Ods.Standard nuget package is missing with package reference for dependencies
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #561
Opened 2022-09-06 04:20 UTC by semalaiappan

2022-09-07 22:00 UTC, bptillman requested changes
Overall things look good here. Just a few changes to make and some and questions I have on some of the changes that were made.

2022-09-08 15:50 UTC, semalaiappan commented on .github/workflows/edFi.ods.api manual.yml
> +        path: ${{ github.workspace }}/NugetPackages/*.*
\Ed-Fi-ODS-Implementation\build.githubactions.ps1  & Ed-Fi-ODS\build.ps1

2022-09-08 16:36 UTC, semalaiappan commented on .github/workflows/edFi.ods.common manual.yml
> +    - name: Checkout Ed-Fi-ODS-Implementation
I removed it but I still need BUILD_INCREMENTER: "17" to get new  EdFi.Suite3.Ods.Common Version="6.0.33" package

2022-09-08 16:37 UTC, semalaiappan commented
![image](https://user-images.githubusercontent.com/34613894/189177499-59678b3f-7d75-4907-aef4-a36b02cbb6f7.png)
EdFi.Ods.Extensions.Sk build succeed with latest package version

2022-09-08 17:11 UTC, semalaiappan commented on .github/workflows/edFi.ods.common manual.yml
> +  BUILD_INCREMENTER: "13"
still need BUILD_INCREMENTER: "17" to get new  EdFi.Suite3.Ods.Common Version="6.0.33" package

2022-09-08 18:26 UTC, semalaiappan commented
<PackageReference Include="EdFi.Suite3.Ods.Api" Version="6.0.32" />
<PackageReference Include="EdFi.Suite3.Ods.Common" Version="6.0.33" />
<PackageReference Include="EdFi.Suite3.Ods.Standard" Version="6.0.22" />

2022-09-08 19:45 UTC, bptillman approved these changes

2022-09-08 19:54 UTC, merged