[ODS-5872] Swagger Add year and tenant dropdowns to swagger UI
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #752
Opened 2023-06-15 22:57 UTC by mjaksn

2023-06-23 22:49 UTC, simpat-jesus requested changes
Looks good, some minor changes and can be merged

2023-06-23 22:49 UTC, simpat-jesus commented on Application/EdFi.Ods.Features/Controllers/OpenApiMetadataController.cs
> +    [Route("{tenantId}/metadata")]
this attribute is not needed; that route template is covered by OdsRouteRootTemplateConvention

2023-06-23 22:49 UTC, simpat-jesus commented on Application/EdFi.Ods.Features/OpenApiMetadata/Providers/EnabledOpenApiMetadataDocumentProvider.cs
> +            _odsContextRoutePath = apiSettings.GetOdsContextRoutePath() ?? "";
replace "" with string.Empty

2023-06-26 14:58 UTC, mjaksn commented on Application/EdFi.Ods.Features/OpenApiMetadata/Providers/EnabledOpenApiMetadataDocumentProvider.cs
> +            _odsContextRoutePath = apiSettings.GetOdsContextRoutePath() ?? "";
Ok, I pushed the changes

2023-06-26 16:54 UTC, merged