[ODS-6075] Update BulkLoad to use OpanAPI v3
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #886
Opened 2023-11-20 18:03 UTC by mjaksn

2023-11-21 20:24 UTC, semalaiappan requested changes
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.BulkLoadClient.Console/overview/7.1.4

I followed steps here https://techdocs.ed-fi.org/pages/viewpage.action?spaceKey=ODSAPIS3V71&title=How+To%3A+Load+the+ODS+with+Sample+XML+Data+using+Bulk+Load+Client+Utility  .  I am getting error ug: EdFi.Ods.Api.Middleware.EdFiOAuthAuthenticationHandler[8]
      AuthenticationScheme: OAuth was successfully authenticated.
2023-11-21 14:23:06,621 [16,(null)] DEBUG EdFiOAuthAuthenticationHandler - AuthenticationScheme: OAuth was successfully authenticated.
2023-11-21 14:23:06,650 [16,3] DEBUG OdsInstanceIdentificationMiddleware - Setting ODS instance '3' (with hash id '3') into context...
2023-11-21 14:23:06,711 [16,3] DEBUG OdsDatabaseConnectionStringProvider - Getting connection string for ODS instance '3' (with hash id '3') from context...
2023-11-21 14:23:06,732 [18,3] DEBUG OdsDatabaseConnectionStringProvider - Getting connection string for ODS instance '3' (with hash id '3') from context...
2023-11-21 14:23:07,015 [18,3] ERROR StaffLeaveEventCategoryDescriptorsController - Post
EdFi.Ods.Common.Security.EdFiSecurityException: Access to the resource could not be authorized for the requested action 'http://ed-fi.org/odsapi/actions/update'.
   at EdFi.Ods.Api.Security.Authorization.AuthorizationBasisMetadataSelector.SelectAuthorizationBasisMetadata(String claimSetName, IList`1 requestResourceClaimUris, String requestAction) in C:\OSS-Workspace\Ed-Fi-ODS\Application\EdFi.Ods.Api\Security\Authorization\AuthorizationBasisMetadataSelector.cs:line 107
   at Castle.Proxies.Invocations.IAuthorizationBasisMetadataSelector_SelectAuthorizationBasisMetadata.InvokeMethodOnTarget()       AuthenticationScheme: OAuth was successfully authenticated.
2023-11-21 14:23:43,618 [16,(null)] DEBUG EdFiOAuthAuthenticationHandler - AuthenticationScheme: OAuth was successfully authenticated.
2023-11-21 14:23:43,636 [16,3] DEBUG OdsInstanceIdentificationMiddleware - Setting ODS instance '3' (with hash id '3') into context...
2023-11-21 14:23:43,692 [16,3] DEBUG OdsDatabaseConnectionStringProvider - Getting connection string for ODS instance '3' (with hash id '3') from context...
2023-11-21 14:23:43,712 [42,3] DEBUG OdsDatabaseConnectionStringProvider - Getting connection string for ODS instance '3' (with hash id '3') from context...
2023-11-21 14:23:43,960 [18,3] ERROR StudentCharacteristicDescriptorsController - Post
EdFi.Ods.Common.Security.EdFiSecurityException: Access to the resource could not be authorized for the requested action 'http://ed-fi.org/odsapi/actions/update'.
   at EdFi.Ods.Api.Security.Authorization.AuthorizationBasisMetadataSelector.SelectAuthorizationBasisMetadata(String claimSetName, IList`1 requestResourceClaimUris, String requestAction) in C:\OSS-Workspace\Ed-Fi-ODS\Application\EdFi.Ods.Api\Security\Authorization\AuthorizationBasisMetadataSelector.cs:line 107
   at Castle.Proxies.Invocations.IAuthorizationBasisMetadataSelector_SelectAuthorizationBasisMetadata.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()

2023-11-21 20:25 UTC, semalaiappan commented
@mjaksn   I need to have all database template build executed successfully from this branch

2023-11-30 04:38 UTC, mjaksn commented
@semalaiappan, all template builds are complete. This is ready for review.

2023-12-05 17:23 UTC, semalaiappan approved these changes

2023-12-05 17:24 UTC, merged