[ODS-5980] Refactor Standard and Extension version optional parameters
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #899
Opened 2023-12-18 15:36 UTC by semalaiappan

2023-12-20 15:45 UTC, simpat-jesus requested changes
Replace hardcoded extension version by using this job https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/blob/08315e57b7fde8849bf6406e17c1904a3889e471/.github/workflows/Pkg%20EdFi.Ods.Minimal.Template.TPDM.yml#L34

2023-12-20 18:45 UTC, semalaiappan commented
@simpat-jesus  Review comments are fixed . Ready for review

2023-12-20 22:32 UTC, simpat-jesus approved these changes

2023-12-20 22:41 UTC, stephenfuqua commented on .github/workflows/Lib edFi.ods.standard manual.yml
> +        .\build.githubactions.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.B
Is this going to work on a Linux build agent?

2023-12-20 22:41 UTC, stephenfuqua commented on .github/workflows/Pkg EdFi.Ods.Minimal.Template.PostgreSQL.yml
> +         Write-host "ExtensionVersions is  $output"
Would it make sense to be consistent here? `echo` and `Write-host` are the same command, so it seems strange to see them both here side by side.

2023-12-21 17:20 UTC, stephenfuqua approved these changes

2023-12-21 17:48 UTC, merged