[ODS-2693] Add integration tests for required extension fields
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #943
Opened 2024-02-03 04:30 UTC by semalaiappan

2024-02-05 20:40 UTC, simpat-jesus requested changes

2024-02-05 20:40 UTC, simpat-jesus commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
> +											"name": "Create Student Parent or Contact Association",
Add a test without extension required properties values to verify those properties are marked as required

2024-02-05 20:40 UTC, simpat-jesus commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
> +									"name": "Create busRoutes",
Add a test without busRouteDirection and operatingCost values to verify those properties are marked as required

2024-02-05 20:40 UTC, simpat-jesus commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
> +									"name": "Post School",
Add a test without careerPathwayDescriptor value to verify the property is marked as required

2024-02-05 20:40 UTC, simpat-jesus commented on Postman Test Suite/Ed-Fi ODS-API Integration Test Suite.postman_collection.json
> +									"name": "Create Staff",
Add a test without pets value to verify the property is marked as required

2024-02-06 02:46 UTC, semalaiappan commented
![image](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/assets/34613894/01d012b4-4710-4291-817c-e410e0d7cc2a)
Added Required Field Validation

2024-02-06 17:15 UTC, simpat-jesus approved these changes

2024-02-06 17:16 UTC, merged