[ODS-6193] Github build and package publish
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #948
Opened 2024-02-07 02:17 UTC by semalaiappan

2024-02-13 15:48 UTC, axelmarquezh requested changes
Please add the 'feature-*' pattern to the list of branches so that the relevant workflows get executed for PRs that target feature branches.

2024-02-14 16:24 UTC, axelmarquezh approved these changes

2024-02-14 18:09 UTC, axelmarquezh commented on .github/workflows/Cleanup Caches by a branch.yml
> +    branches: [main, b-v*-patch*,feature-*]
I think we should include the quotes, at least that's how it appears in GitHub examples:
![image](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/assets/158314644/f313194b-9aa5-42df-b4cd-9cc16ab33ddc)

2024-02-14 19:19 UTC, vimayya approved these changes

2024-02-14 19:20 UTC, merged

2024-02-14 20:06 UTC, semalaiappan commented
verified - publish for below packages name: Lib EdFi.Admin.DataAccess
name: Lib EdFi.Common
name: Lib EdFi.LoadTools
name: Lib EdFi.Ods.Api
name: Lib EdFi.Ods.Common
name: Lib EdFi.Ods.Standard
name: Lib EdFi.Security.DataAccess