[ODS-6288] Rebase Epic branch (ODS-6105)
Ed-Fi-Alliance-OSS/Ed-Fi-ODS pull request #995
Opened 2024-03-08 01:41 UTC by semalaiappan

2024-03-09 01:08 UTC, simpat-jesus requested changes

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Common/Exceptions/ApiSecurityConfigurationException.cs
> +// SPDX-License-Identifier: Apache-2.0
This file was removed in ODS-6139

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Common/Models/Resource/ProfileContentTypeException.cs
> +// SPDX-License-Identifier: Apache-2.0
This file was removed in ODS-6139

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Common/Exceptions/DistributedCacheException.cs
> +
I don't see this conde in ODS-6139 commit, was it added as part of the migration to .net 8?

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Common/Security/EdFiSecurityConflictException.cs
> +﻿// SPDX-License-Identifier: Apache-2.0
This file was removed in ODS-6139

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Common/Security/EdFiSecurityException.cs
> +﻿// SPDX-License-Identifier: Apache-2.0
This file was removed in ODS-6139

2024-03-09 01:08 UTC, simpat-jesus commented on Application/EdFi.Ods.Features/Notifications/Redis/InitializeRedisNotifications.cs
> +    [Obsolete]
Is this needed to supress a warning? I don't remember it being as part of one of the .NET 8 migration tickets

2024-03-09 01:11 UTC, simpat-jesus commented
We also need to remove the customizations pulled from .NET 8 for tickets [ODS-6185](https://tracker.ed-fi.org/browse/ODS-6185) and [ODS-6139](https://tracker.ed-fi.org/browse/ODS-6139)

2024-03-13 17:11 UTC, simpat-jesus approved these changes

2024-03-13 19:23 UTC, simpat-jesus approved these changes

2024-03-13 19:45 UTC, vimayya approved these changes

2024-03-13 19:47 UTC, merged